### ISSUE TITLE
Add an option to change default cli prompt

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#114]
See the discussion here:

http://redisdoc.com/transaction/exec.html#comment-4588712198

https://stackoverflow.com/questions/52690515/change-redis-command-prompt-text/52691005

**Comment by guoweikuang** [comment]
I don't think it's necessary, so I can know more clearly that I am currently on the redis server.

**Comment by laixintao** [comment]
@guoweikuang Yes normally you don't need this, only if you want to make the prompt shorter on purpose. 

For example, your redis domain name is too long.

When you do this, like `--prompt={host}` (yes, wen can let user setting it with python's template), I think you already know what you are doing.

**Comment by laixintao** [comment]
The usage like this:
```
$ iredis --prompt='{host[:10]}'  # set hostname max length is 10

$ iredis --prompt='{host[:10]:{port}[{db}]'

$ iredis --prompt='{port}' # only show port on prompt
```

**Comment by laixintao** [comment]
Client source port is supported.

**Comment by laixintao** [comment]
connection id?

**Comment by laixintao** [comment]
server cluster name;
server role(master/slave)

**Comment by aymericbeaumet** [comment]
I'm embedding iredis into an in-house CLI for our engineering team, and the `--prompt` flag could come handy (supported by some other tools like https://github.com/dbcli/pgcli).

Would you accept a PR in that direction?

**Comment by laixintao** [comment]
@aymericbeaumet sure thing. Is https://github.com/laixintao/iredis/issues/114#issuecomment-525271496 looks good to you?

and what placeholders do you want?
currently what I can come with are:
- host
- port
- db number
- client id?
- client port?
- current username used to auth?

any others?

**Comment by aymericbeaumet** [comment]
> @aymericbeaumet sure thing. Is https://github.com/laixintao/iredis/issues/114#issuecomment-525271496 looks good to you?

Yes, that should be doable using some kind of template engine (I'm not a Python developer).

> currently what I can come with are:

**Comment by aymericbeaumet** [comment]
@laixintao ready for review: https://github.com/laixintao/iredis/pull/437

**Comment by laixintao** [comment]
@aymericbeaumet iredis 1.12.1 released, enjoy.
https://github.com/laixintao/iredis/releases/tag/v1.12.1

FYI, documentation updated:

### Change The Default Prompt

You can change the prompt str, the default prompt is:

```shell
127.0.0.1:6379>
```

Which is rendered by `{host}:{port}[{db}]> `, you can change this via `--prompt` option or change
[iredisrc](https://github.com/laixintao/iredis/blob/master/iredis/data/iredisrc)
config file. The prompwt string uses python string format engine, supported
interpolations:

- `{client_name}`
- `{db}`
- `{host}`
- `{path}`
- `{port}`
- `{username}`
- `{client_addr}`
- `{client_id}`

The `--prompt` utilize
[Python String format engine](https://docs.python.org/3/library/string.html#formatstrings),
so as long as it is a valid string formatter, it will work( anything that
`"<your prompt>".format(...)` accepts). For example, you can limit your Redis
server host name's length to 5 by setting `--prompt` to
`iredis --prompt '{host:.5s}'`.

**Comment by aymericbeaumet** [comment]
@laixintao Great work thanks!
