### ISSUE TITLE
load dotfile and keyword_casing 

### ISSUE THREAD

**Issue by tinyRatP** [laixintao/iredis#194]
iredis should load  config from `.iredis.conf`. 

The feature:  setting keyword_casing(like set, get,  lpush etc..) just like others.

![image](https://user-images.githubusercontent.com/15377472/71944943-4eb38c80-3200-11ea-8ea9-f1b9bb4b9941.png)

Is it worth doing? If do, I will give it a try.

**Comment by laixintao** [comment]
Yes config file supporting was on the plan. see also https://github.com/laixintao/iredis/issues/191

But I don't understand `keyword_casing` exactly, what is that for? Any example or effect?

**Comment by tinyRatP** [comment]
Automatically uppercase/lowercase keywords(like `SET, GET, LPUSH, HSET`) in redis during using tab to auto-completion

**Comment by laixintao** [comment]
I see, yes this is good idea.

Currently the lowercase/uppercase are based on the user input(like your keyword_casing=auto, in your description), like this:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/9675939/72033441-4b3a0700-32cd-11ea-95ea-ebe2d5562322.png">

<img width="485" alt="image" src="https://user-images.githubusercontent.com/9675939/72033454-54c36f00-32cd-11ea-9a18-64763d8a882c.png">

But I think we can add an option to, for example, use the uppercase command only.

Can we call this option like `--command-casing`? `keyword` appeared on some Redis command reference, so it can be confusing.

**Comment by tinyRatP** [comment]
I'm not skilled in redis, Maybe we can call it `command-casing`.

**Comment by laixintao** [comment]
Hi @tinyRatP 
This feature has been released to v1.0.5 

Please upgrade 🎉
