### ISSUE TITLE
Package a binary with https://github.com/indygreg/PyOxidizer?

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#218]

**Comment by mac-chaffee** [comment]
+1 on this issue! My use-case is I run redis in docker containers, so I'd like to be able to quickly `curl` down an iredis binary for debugging live systems that don't have python installed.

I started working on this here: https://github.com/laixintao/iredis/commit/1c824ee5d1b5b81752688268f51b071267dce173

I've hit an issue where [iredis uses  `__file__`](https://github.com/laixintao/iredis/blob/v1.0.0/iredis/__init__.py#L8), but PyOxidizer doesn't set the `__file__` attribute: https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#reliance-on-file

I'll keep searching for a work-around

**Comment by laixintao** [comment]
Hi @mac-chaffee Thanks! The commit is a good start.

I found a page of PyOxidizer here: https://pyoxidizer.readthedocs.io/en/stable/packaging_pitfalls.html  Maybe we can remove the usage of `__file__`

**Comment by laixintao** [comment]
Hi @mac-chaffee, can you open a work-in-process PR so I can see your work?

I have a question by the way, where is the best place for the package to be uploaded to?

**Comment by mac-chaffee** [comment]
Hmm that's a good question! I could update the circleci step to [save the binary as an artifact](https://circleci.com/docs/2.0/artifacts/), then when you create the next release, you could upload that file as an "asset" here: https://github.com/laixintao/iredis/releases

That's one option, but since you'd be the one uploading this binary, I can do whatever's easiest for you

**Comment by laixintao** [comment]
That's awesome! I don't even know you can upload the binary to Github release before, let's store the binary there.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/9675939/74807104-9ad70e00-5322-11ea-9ed4-0e63d52322fb.png">

You can leave the artifact on circleci, I will figure out using circleci to automatic upload: https://circleci.com/blog/supporting-digital-transformation-while-avoiding-common-stalls/

**Comment by laixintao** [comment]
Hi @mac-chaffee 

Have you read this? https://pyoxidizer.readthedocs.io/en/stable/packaging.html#packaging-additional-files

I found it very interesting, I think it's workable by packaging the libs IRedis depended on (e.g. pendulum) into a lib dir. But I haven't tried it yet. FYI.

BTW, I found that I can use Github Action to auto-upload the built artifact to release page and there is the [latest release](https://help.github.com/en/github/administering-a-repository/linking-to-releases) link we can share on the readme. So the "where to store binary" issue was resolved. :)

**Comment by mac-chaffee** [comment]
Hmm good find! I'll try that out next. Sure beats my strategy of trying to audit every single dependency for usage of `__file__`.

It unfortunately does mean we can't just `curl` a single binary though. But I guess it's not too bad to curl a tar file which contains the executable and the libraries.

**Comment by mac-chaffee** [comment]
From my tests, your suggestion worked @laixintao; I was able to build a binary with the python dependencies packages separately using that link.

Working now on making Github Actions build and tar up the executable

**Comment by mac-chaffee** [comment]
Thought I'd give another update: I've been working on getting Github Actions to automatically create a release and upload the binary (which means a lot of force-pushing the same commit and tag to my fork, thus I've been holding off on creating a new PR). Sort of worked here (tested by uploading the source tar.gz): https://github.com/mac-chaffee/iredis/runs/468576407

Working out an issue now where the binary reports that the iredis package is missing.

**Comment by laixintao** [comment]
Your work is remarkable! Special thanks to you! ❤️

> Working out an issue now where the binary reports that the iredis package is missing.

I didn't get it, I downloaded the package here: https://github.com/mac-chaffee/iredis/releases/download/v27.0.8/iredis.tar.gz and it works good. Is this PR ready to merge?

**Comment by mac-chaffee** [comment]
Yes I fixed the issue. I accidentally removed a random line of code which broke it haha

**Comment by laixintao** [comment]
So I think I can merge this now? Look good to me :)

**Comment by mac-chaffee** [comment]
Yep sounds good! Thanks for your patience!

**Comment by laixintao** [comment]
I should thank you for your excellent work! Well done!

**Comment by laixintao** [comment]
fixed by https://github.com/laixintao/iredis/pull/279
