### ISSUE TITLE
help command not working

### ISSUE THREAD

**Issue by lau-jay** [laixintao/iredis#230]
# Question
help command first can show doc, but if you help can't get doc detail,  run the first command again.
you can't get doc detail again.

#  Example
## First
```
127.0.0.1:6379> help set

  SET
  summary: Set the string value of a key
  complexity: O(1)
  since: 1.0.0 (Avaiable on your redis-server: 5.0.3)
  group: string
  syntax: SET key value [expiration [EX seconds|PX milliseconds]] [NX|XX]

Set key to hold the string value.
If key already holds a va......

```
##  Second

```
127.0.0.1:6379> help setnx
(error) can only concatenate str (not "NoneType") to str
127.0.0.1:6379>
```

## First Again
```
127.0.0.1:6379> help set
(error) 'Markdown' object has no attribute 'output_list_end'
127.0.0.1:6379>
```

**Comment by laixintao** [comment]
Thanks for reporting! Will fix in next release.

**Comment by laixintao** [comment]
This is because the parser returned None for the 3rd markdown header. And there is a h3 in this doc.

I will look for a better lib to display markdown in shell.
