### ISSUE TITLE
Alternative to replace mistune, render markdown in shell

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#232]
- https://github.com/ttscoff/mdless/
- https://github.com/visit1985/mdp
- bat

**Comment by laixintao** [comment]
https://github.com/lunaryorn/mdcat

**Comment by sebix** [comment]
Is there any update on this? mistune upstream is already at version 2.0.1, but iredis depends on mistune < 0.9 and fails to build with the current version. That means, iredis is practically impossible to package in distros because of that incompatibility.

```
[    5s] + pytest --ignore=_build.python3 -v -k 'not test_abort_reading_connection'
[    5s] ImportError while loading conftest '/home/abuild/rpmbuild/BUILD/iredis-1.10.0/tests/conftest.py'.
[    5s] tests/conftest.py:9: in <module>
[    5s]     from iredis.client import Client
[    5s] iredis/client.py:24: in <module>
[    5s]     from . import markdown, renders
[    5s] iredis/markdown.py:16: in <module>
[    5s]     class TerminalRender(mistune.Renderer):
[    5s] E   AttributeError: module 'mistune' has no attribute 'Renderer'
```

**Comment by laixintao** [comment]
hi @sebix thanks for telling me this.

I have no plan for replacing mistune anymore.

However, I need to upgrade mistune to ^2.0 asap :)

**Comment by sebix** [comment]
> However, I need to upgrade mistune to ^2.0 asap :)

That is an option as well ;)

**Comment by laixintao** [comment]
forgot to mention that: the reason that I stick with mistune is that:

1. It would be better if we can translate markdown to some format that https://github.com/prompt-toolkit/python-prompt-toolkit (which iredis is based on) can understand so that we can use the same style with other iredis outputs. Also we can have other features provided by https://github.com/prompt-toolkit/python-prompt-toolkit, like pager. I have considered libs like https://github.com/Textualize/rich, which write rendered content to stdout directly, but decided to keep with mistune.
2. mistine is a very small lib (no dependencies!)

(FYI and also for the future me to refer.)

**Comment by sebix** [comment]
I'm want to get iredis packaged in openSUSE, but I can't due to the version mismatch of mistune. We have mistune 2.0.1, but that does not work with iredis :/

**Comment by laixintao** [comment]
awesome. thanks for the packaging work. I will release a new version of iredis for updating the dependencies tonight. :)

**Comment by laixintao** [comment]
it was fixed and released in https://github.com/laixintao/iredis/releases/tag/v1.11.0

good luck packaging!

**Comment by sebix** [comment]
Thanks, have some test fails on i586, will open an issue on them.
