### ISSUE TITLE
操作系统中不存在"HOME"变量，报错

### ISSUE THREAD

**Issue by Littlecowherd** [laixintao/iredis#256]
OS Version：Windows 10 1909
Python version：3.7.3
iredis version：0.9.0

问题截图：
![image](https://user-images.githubusercontent.com/19882756/74520908-73afc380-4f53-11ea-8874-35a5f371e48b.png)

解决方案：
查了下 windows 存放用户主目录的环境变量为：%HOMEPATH%，更改后可用。
![image](https://user-images.githubusercontent.com/19882756/74521838-0b61e180-4f55-11ea-9a58-cdda16b5e312.png)
感觉这里加上默认路径，或者判断下操作系统会好一点吧

**Comment by laixintao** [comment]
Hi 感谢报告错误，iredis 没有在 windows 下测试过，看起来比我预期的工作的要好啊，只有这一个错误。

log 的位置我打算放在 ~/.iredisrc 中允许用户自定义配置的，我尽快合并这个配置项；

另外还没有很多精力完善在 Windows 下的测试，如果您遇到其他的问题欢迎提交 issue.

**Comment by laixintao** [comment]
Hi 现在 iredisrc 配置文件可以自己配置log的地址了，默认是关闭log的。

请尝试下载 iredis v1.0 试试， `pip install iredis` 应该不会出现这个问题了。

**Comment by Adam-Jin** [comment]
@Littlecowherd 请问在windows下如何使用？

**Comment by Adam-Jin** [comment]
@Littlecowherd 请问windows下如何使用？

**Comment by laixintao** [comment]
Hi

请用 pip install iredis 尝试一下，我没有windows，所以没有完整测试过，sorry。我还在想办法在 windows 上开发。
