### ISSUE TITLE
Does config file support alias_dsn section?

### ISSUE THREAD

**Issue by lyqscmy** [laixintao/iredis#268]
Does iredisrc support alias_dsn section like in myclirc? If not, how to contribute? By now, I work around by alias in bash .profile.

**Comment by laixintao** [comment]
Currently no, but alias_dsn is a nice feature to have!

If you want to contribute, you can start at adding an `alias_dsn` option to `iredisrc`. The config loading happens here: https://github.com/laixintao/iredis/blob/72c42914987f7e76699fd30e5f389e943c66fac5/iredis/config.py#L87

And iredis use lib click to parse command line args, the entry is here: https://github.com/laixintao/iredis/blob/72c42914987f7e76699fd30e5f389e943c66fac5/iredis/entry.py#L198

**Comment by laixintao** [comment]
BY #271
