### ISSUE TITLE
[Rust] Github Action: Cache for cargo build.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#283]
Currently, PyOxidizer will compile for every release, which is time consuming.

https://github.com/laixintao/iredis/runs/471363937

related:
#218 
#279

**Comment by laixintao** [comment]
```
If the source is crates.io or `--git` then by default the crate will be built
in a temporary target directory. To avoid this, the target directory can be
specified by setting the `CARGO_TARGET_DIR` environment variable to a relative
path. In particular, this can be useful for caching build artifacts on
continuous integration systems.
```

`CARGO_TARGET_DIR` for cargo install.

**Comment by laixintao** [comment]
http://johanengelen.github.io/ldc/2016/11/10/Link-Time-Optimization-LDC.html

**Comment by messense** [comment]
This won't be needed if https://github.com/indygreg/PyOxidizer/pull/385 gets accepted, then you can install PyOxidizer with just `pip install pyoxidizer`.

**Comment by laixintao** [comment]
@messense Thanks!
