### ISSUE TITLE
Auto redirect in redis-cluster.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#325]
If a key not in the connected node, auto redirect to correct node.

**Comment by youguanxinqing** [comment]
So, the feature is not supported ?  I tried to connect redis cluster by iredis, it's ok, but it seemd no auto redirect when a key not in the node.

**Comment by laixintao** [comment]
Yes sorry, this feature is not supported currently, I will do it ASAP :)

I Will let you know when it's done.

**Comment by youguanxinqing** [comment]
Thanks for your effort ! Iredis is convient, I love it.

**Comment by laixintao** [comment]
It's done and released in version https://github.com/laixintao/iredis/releases/tag/v1.9.1

Please upgrade.
