### ISSUE TITLE
iredis config file format check

### ISSUE THREAD

**Issue by lau-jay** [laixintao/iredis#354]
if .iredisrc format wrong, I think need raise or warning like Nginx

**Comment by laixintao** [comment]
Thanks, it's difficult but I will try to do some basic check.

**Comment by lau-jay** [comment]
Maybe give a .iredisrc template(all section comment)  to easy copy and edit?

**Comment by laixintao** [comment]
Yes, You can copy from here:

https://github.com/laixintao/iredis#configuration (which will lead you here: https://raw.githubusercontent.com/laixintao/iredis/master/iredis/data/iredisrc )
