### ISSUE TITLE
ERROR a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by bit-ranger** [laixintao/iredis#383]
using
iredis --decode=utf-8 -d xxx

![image](https://user-images.githubusercontent.com/6255739/115340979-5111de00-a1da-11eb-98b9-472d26e53876.png)

**Comment by codingknees** [comment]
加了--decode选项才会出现

**Comment by Hanaasagi** [comment]
If use the `decode_responses` option in Redis. `redis_resp` will be a string type. The `input` argument  of `subprocess.run` should be a byte sequence or a string when `text` is `true`.

https://github.com/laixintao/iredis/blob/886956e2db694b29d23d52d2e459fa2c30098ba8/iredis/client.py#L406-L416

**Comment by laixintao** [comment]
thanks @Hanaasagi  for the fix, I have released v1.9.3.
https://github.com/laixintao/iredis/commit/c31f7a882bcda823cfa53d63217abfd4f4cdf13d

You can update to the latest version. @bit-ranger <3
