### ISSUE TITLE
Please upgrade importlib-resources

### ISSUE THREAD

**Issue by nvpe** [laixintao/iredis#388]
Version conflict with `mycli` and `iredis`

There are incompatible versions in the resolved dependencies:
  importlib-resources==1.0.2 (from iredis==1.9.1->-r requirements.in (line 18))
  importlib-resources>=5.0.0 (from mycli==1.24.1->-r requirements.in (line 16))

**Comment by laixintao** [comment]
hi @nvpe  please try v1.9.2

just released.

**Comment by nvpe** [comment]
Thanks @laixintao, it worked.
