### ISSUE TITLE
cannot install on mac

### ISSUE THREAD

**Issue by SamSalvatore** [laixintao/iredis#399]
➜  brew install iredis
==> Searching for similarly named formulae...
These similarly named formulae were found:
hiredis                                   redis ✔                                   ired
To install one of them, run (for example):
  brew install hiredis
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by SamSalvatore** [comment]
➜  iredis brew install iredis
Updating Homebrew...
==> Searching for similarly named formulae...
These similarly named formulae were found:
hiredis ✔                                 redis ✔                                   ired ✔
To install one of them, run (for example):
  brew install hiredis ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by laixintao** [comment]
can you run `brew update` first?
