### ISSUE TITLE
[bug]: Paramter client_name not working with redis-py before v3.4.0

### ISSUE THREAD

**Issue by MerleLiuKun** [laixintao/iredis#400]
for redis-py client_name add at [v3.4.0](https://github.com/andymccurdy/redis-py/blob/master/CHANGES#L87) and for iredis with dependency `redis = "^3"`.

So, maybe we need to do sth for this.

ps. I found it in one old project:)

**Comment by MerleLiuKun** [comment]
cc @laixintao

**Comment by laixintao** [comment]
Hi, how about the we pin the version of redis-py to `^3.4.0`?

We maintain multiple version support for redis-server, but I don't want to be compatible to multiple `redis-py`.

Do you have problems upgrading redis-py? e.g. do you have problems to install iredis in a separated environment?

**Comment by MerleLiuKun** [comment]
Yes, I prefer to pin the version to `^3.4.0`.

I have no problems for upgrading redis-py, this only for my  tests in a old environment. :)
