### ISSUE TITLE
Upgrade to mistune 2.0

### ISSUE THREAD

**Issue by daniel-baumann** [laixintao/iredis#415]
Hi,

iredis depends on the Python mistune module.

The current version of mistune is 2.0 and is backwards incompatible with mistune 0.8, which is currently used.

It would be nice if you could support using mistune 2.0, as 0.8 is going away in Debian soon, see:
https://bugs.debian.org/1003572

Regards,
Daniel

**Comment by laixintao** [comment]
hi @daniel-baumann thanks for reporting.

It was fixed at #416 , and released https://github.com/laixintao/iredis/releases/tag/v1.11.0
