### ISSUE TITLE
Configure the .iredisrc file, connect through -d, and report an error

### ISSUE THREAD

**Issue by pizsd** [laixintao/iredis#426]
python version：Python 3.10.2
iredis version：version 1.11.0
I don't know python very well. I want to know what kind of problem this is and how to deal with it?
<img width="916" alt="image" src="https://user-images.githubusercontent.com/53469108/173809894-00443b45-9e99-45c2-98f4-438c0d0415ed.png">

**Comment by laixintao** [comment]
hi @pizsd I believe it was a known bug and fixed in 1.11.1 https://github.com/laixintao/iredis/blob/master/CHANGELOG.md#1111

can you try to upgrade?
