### ISSUE TITLE
How do I connect to redis by SSH Tunnel?

### ISSUE THREAD

**Issue by Kevalin** [laixintao/iredis#434]
I manage diffenrent envs by dsn. But I don't know how to connect to Redis by ssh tunnel.
Can u help me? thx :)

**Comment by laixintao** [comment]
SSH tunnel should make a transparent port ready to be connected, there is no special configuration for IRedis to connection such port, just use `iredis -p <port>` to connect the reversed port.

**Comment by Kevalin** [comment]
> SSH tunnel should make a transparent port ready to be connected, there is no special configuration for IRedis to connection such port, just use `iredis -p <port>` to connect the reversed port.

Thanks for your reply!
I had a try, but I can't find enough options to connect my SSH tunnel. For example:
```bash
iredis -h <ssh-host> -p <ssh-port> -u <ssh-user> -i <ssh-private-key>
```

**Comment by Kevalin** [comment]
thanks for your reply!
I success to connect my Redis server.
```bash
## Create a ssh tunnel
ssh -L [local_ip:]local_port:destination_host:destination_port -N -f [ssh_user@]ssh_server -p ssh_port -i private_key

## Connect
iredis -p <local_port> -a <passwd> -n <database_number>
```
It's nice!

**Comment by laixintao** [comment]
You are awesome too!
