### ISSUE TITLE
Retiring Python3.6 support.

### ISSUE THREAD

**Issue by laixintao** [laixintao/iredis#448]

**Comment by Lotram** [comment]
@laixintao I think you can close this issue, since you dropped Python3.6 in [this commit](https://github.com/laixintao/iredis/commit/9a9b1657aaba7a48f3f31ecb526445b69a5c8c3d#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R33)

**Comment by laixintao** [comment]
thanks @Lotram
