### ISSUE TITLE
Ignore y/n prompt

### ISSUE THREAD

**Issue by heowc** [laixintao/iredis#457]
hello. I am using `iredis`. 👍 

I often want to ignore "Do you want to proceed" when using KEYS or DEL. Is there any way to override this?

**Comment by laixintao** [comment]
Hi, yes.

You can create a file called `~/.iredisrc` and put follows:

```
[main]
warning = False
```

config file example and docs here:

https://github.com/laixintao/iredis/blob/master/iredis/data/iredisrc#L52
